CREATE TABLE IF NOT EXISTS devices (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	token TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS devices_token_unique ON devices (token);

-- ts is unix time in milliseconds
CREATE TABLE IF NOT EXISTS events (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	ts INTEGER NOT NULL,
	device INTEGER NOT NULL,
	FOREIGN KEY (device) REFERENCES devices(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);
